#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Happimeter.Watch.Droid.Resource", IsApplication=true)]

namespace Happimeter.Watch.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050001
			public const int AccX = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int AccY = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int AccZ = 2131034115;
			
			// aapt resource value: 0x7f05000d
			public const int ExchangeAtLabel = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int ExchangeAtValue = 2131034126;
			
			// aapt resource value: 0x7f050000
			public const int LabelAccel = 2131034112;
			
			// aapt resource value: 0x7f050004
			public const int NumberOfEntries = 2131034116;
			
			// aapt resource value: 0x7f05000b
			public const int PairedAtLabel = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int PairedAtValue = 2131034124;
			
			// aapt resource value: 0x7f050005
			public const int TimeStamp = 2131034117;
			
			// aapt resource value: 0x7f050009
			public const int isPairedLabel = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int isPairedValue = 2131034122;
			
			// aapt resource value: 0x7f050006
			public const int linearLayout1 = 2131034118;
			
			// aapt resource value: 0x7f050008
			public const int linearLayout2 = 2131034120;
			
			// aapt resource value: 0x7f05000f
			public const int removePairingButton = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int restartWorker = 2131034128;
			
			// aapt resource value: 0x7f050007
			public const int textView1 = 2131034119;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
